# yamllint disable rule:comments-indentation
---
theme: light #light/dark/grey/auto

default_redirection_url: https://auth.origin.univrs.cloud/ #where to redirect for a non-existent URL

jwt_secret: virgoOS_123 #any text or number you want to add here to create jwt Token

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log:
  level: debug

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m
  file:
    path: /config/users.yml #this is where your authorized users are stored
    password:
      algorithm: bcrypt
      bcrypt:
        variant: standard
        cost: 12

access_control:
  default_policy: one_factor
  rules:
  - domain: "auth.origin.univrs.cloud" #this should be your authentication URL
    policy: bypass
  - domain: "*.origin.univrs.cloud"
    policy: bypass
    networks:
      - 192.168.0.0/16 #bypass if connected on local network
      - 10.6.0.0/16 #bypass if connected over VPN

session:
  name: virgoOS
  secret: virgoOS_123 #any text or number you want to add here to create jwt Token
  expiration: 3600  #1 hour
  inactivity: 300  #5 minutes
  domain: origin.univrs.cloud  #should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  local:
    path: /config/db.sqlite3
  encryption_key: virgoOS_you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this

notifier:
  disable_startup_check: true
  filesystem:
    filename: /config/notification.txt
...
