version: "3.0"

services:
  pihole:
    container_name: pihole
    image: cbcrowe/pihole-unbound:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    ports:
      - 443:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - ${WEBPORT:-8000}:80/tcp #Allows use of different port to access pihole web interface when other docker containers use port 80
    environment:
      - FTLCONF_LOCAL_IPV4=${FTLCONF_LOCAL_IPV4}
      - TZ=${TZ:-UTC}
      - WEBPASSWORD=${WEBPASSWORD}
      - PIHOLE_DNS_=127.0.0.1#5335
      - DNSSEC=false
      - DNSMASQ_LISTENING=single
    volumes:
      - /portainer/Files/AppData/Config/pihole:/etc/pihole
      - /portainer/Files/AppData/Config/pihole/dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
    
