version: "3"
services:
  pihole:
    image: cbcrowe/pihole-unbound:latest
    container_name: pihole
    environment:
      - TZ=${TZ}
      - WEBPASSWORD=${WEBPASSWORD}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - FTLCONF_LOCAL_IPV4=${FTLCONF_LOCAL_IPV4}
      - DNSMASQ_LISTENING=all
      - PIHOLE_DOMAIN=${DOMAIN_NAME}
      - PIHOLE_DNS_=127.0.0.1#5335;127.0.0.1#5335
      - DHCP_ACTIVE=${DHCP_ACTIVE}
      - DHCP_START=${DHCP_START}
      - DHCP_END=${DHCP_END}
      - DHCP_ROUTER=${DHCP_ROUTER}
      - DHCP_rapid_commit=true
    volumes:
      - /portainer/etc-pihole/:/etc/pihole/
      - /portainer/etc-dnsmasq.d/:/etc/dnsmasq.d/
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "8000:80/tcp"
    depends_on:
      - dhcphelper
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
    networks:
      app_net:
        ipv4_address: 172.26.0.2
    restart: unless-stopped

  dhcphelper:
    container_name: dhcphelper
    image: homeall/dhcphelper:latest
    network_mode: "host"
    environment:
      IP: 172.26.0.2
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16
          gateway: 172.26.0.1
