version: "2"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    mac_address: "d0:ca:ab:cd:ef:01"
    cap_add:
      - NET_ADMIN
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
      - 22/tcp
    environment:
      - FTLCONF_LOCAL_IPV4=192.168.100.201
      - VIRTUAL_HOST=${HOSTNAME}
      - PIHOLE_DOMAIN=${DOMAIN_NAME}
      - WEB_PORT=8080
      - WEBPASSWORD=${WEBPASSWORD}
      - DHCP_ACTIVE=true
      - DHCP_START=192.168.100.100
      - DHCP_END=192.168.100.250
      - PIHOLE_DNS_=192.168.100.202
    volumes:
      - /portainer/Files/AppData/Config/pihole:/etc/pihole:rw
      - /portainer/Files/AppData/Config/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
    networks:
      home:
        ipv4_address: 192.168.100.201
    restart: always
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    hostname: unbound
    mac_address: "d0:ca:ab:cd:ef:02"
    ports:
      - 53/tcp
      - 53/udp
    networks:
      home:
        ipv4_address: 192.168.100.202
    restart: always

networks:
  home:
    driver: macvlan
    driver_opts:
      parent: wlan0
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1
          ip_range: 192.168.100.201/30
